spring:
  datasource:
    url: jdbc:postgresql://db:5432/urlshortener_dev
    username: urlshortener
    password: urlshortener
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      database: ${REDIS_DATABASE:1}
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 1
          max-wait: -1ms
        shutdown-timeout: 100ms

cache:
  ttl-minutes: ${CACHE_TTL_MINUTES:3}