spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:staging-db-host}:5432/urlshortener_staging
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  redis:
    host: ${REDIS_HOST:staging-redis-host}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 3
    timeout: 2000

cache:
  ttl-minutes: ${CACHE_TTL_MINUTES:5} 