spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER:postgres:urlshortener}
    password: ${POSTGRES_PASSWORD:password:urlshortener}
    driver-class-name: org.postgresql.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 1
    timeout: 2000

cache:
  ttl-minutes: ${CACHE_TTL_MINUTES:10}