
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: urlshortener_dev
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - urlshortener-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes
    networks:
      - urlshortener-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/urlshortener_dev
      SPRING_DATASOURCE_USERNAME: urlshortener
      SPRING_DATASOURCE_PASSWORD: urlshortener
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      # Set the active Spring profile (dev, staging, prod)
      SPRING_PROFILES_ACTIVE: dev
      # For staging, uncomment the following line:
      # SPRING_PROFILES_ACTIVE: staging
    networks:
      - urlshortener-network

volumes:
  pgdata:
  redisdata:

networks:
  urlshortener-network:
    driver: bridge 